name: wuxuegongcao
on:
  workflow_dispatch:

  schedule:
    - cron: '6 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wuxuegongcao
        env:
          tqoc8455: ${{ secrets.tqoc8455 }}
        run: |
          printf '%s' "$tqoc8455" | jq -r .h9 | /bin/bash
          echo $a6 | jq -r .b95 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: THS1KwiM
          path: "*.zip"
          retention-days: 1
